#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2018 Raphiel Rollerscaperers (raphielscape)
# Copyright (C) 2019 Muhammad Fadly Ardhians (Mmhmdfas)
# Kernel Build Script

echo "Main Environment"
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
echo "Clone Toolchain"
git clone -j32 https://github.com/najahiiii/priv-toolchains.git -b non-elf/gcc-9.2.0/arm64 gcc
git clone -j33 https://github.com/najahiiii/priv-toolchains.git -b non-elf/gcc-9.2.0/arm gcc32
git clone -j32 https://github.com/NusantaraDevs/DragonTC dtc
git clone -j32 https://github.com/Mmhmdfas/anykernel3.git
echo "Done"
GCC="$(pwd)/gcc/bin/aarch64-linux-gnu-"
GCC32="$(pwd)/gcc32/bin/arm-linux-gnueabi-"
CT="$(pwd)/dtc/bin/clang"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=DarkEagle
export KBUILD_BUILD_HOST=Buildbot
TOOLCHAIN=$(cat out/include/generated/compile.h | grep LINUX_COMPILER | cut -d '"' -f2)
UTS=$(cat out/include/generated/compile.h | grep UTS_VERSION | cut -d '"' -f2)
KERNEL=$(cat out/.config | grep Linux/arm64 | cut -d " " -f3)
# sticker plox
function sticker() {
        curl -s -X POST "https://api.telegram.org/bot905061652:AAHKYGa3P9xkLoCK52RjDNW8s-AEf6twhNQ/sendSticker" \
                        -d sticker="CAADBQADCAEAAn1Cwy6ay-eWBf1msRYE" \
                        -d chat_id=-1001168028608
}
# Send info plox
function sendinfo() {
        curl -s -X POST "https://api.telegram.org/bot905061652:AAHKYGa3P9xkLoCK52RjDNW8s-AEf6twhNQ/sendMessage" \
                        -d chat_id=-1001168028608 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="<b>DarkEagle</b> new build is up%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code> (Android 9.0/Pie)%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler: <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Build Status:</b> #untested"
}
# Send info plox
function sendinfo() {
        curl -s -X POST "https://api.telegram.org/bot905061652:AAHKYGa3P9xkLoCK52RjDNW8s-AEf6twhNQ/sendMessage" \
                        -d chat_id=-1001168028608 \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="<b>New Build Is Coming!!</b>" \
                                     "<b>For device :</b>Xiaomi Redmi 4A <code>(ROLEX)</code>" \
                                     "<b>Kernel version :</b> <code>Linux ${KERNEL}</code>" \
                                     "<b>From Branch :</b> <code>$(git rev-parse --abbrev-ref HEAD)</code>" \
                                     "<b>Under commit :</b> <code>$(git log --pretty=format:'"%h : %s"' -1)</code>" \
                                     "<b>Toolchain :</b> <code>${TOOLCHAIN}</code>" \
                                     "<b>UTS version :</b> <code>${UTS}</code>"
}
# Push kernel to channel
function push() {
        cd anykernel3
	ZIP=$(echo dark*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot905061652:AAHKYGa3P9xkLoCK52RjDNW8s-AEf6twhNQ/sendDocument" \
			-F chat_id="-1001168028608" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | #sunny"
}
# Fin Error
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot905061652:AAHKYGa3P9xkLoCK52RjDNW8s-AEf6twhNQ/sendMessage" \
			-d chat_id="-1001168028608" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Build throw an error(s) | **Build logs** [here](${HASIL})"
        exit 1
}
# Compile plox
function compile() {
        make -s -C $(pwd) O=out rolex_defconfig
        make -s -C $(pwd) CC=${CT} CROSS_COMPILE_ARM32=${GCC32} CROSS_COMPILE=${GCC} O=out -j32 -l32 2>&1| tee build.log
            if ! [ -a $IMAGE ]; then
                finerr
                exit 1
            fi
        cp out/arch/arm64/boot/Image.gz-dtb anykernel3/zImage
        paste
}
# Zipping
function zipping() {
        cd anykernel3
        zip -r9 darkeagle-pie-${tanggal}.zip *
        cd ..
}
sticker
sendinfo
sendpriv
compile
zipping
END=$(date +"%s")
DIFF=$(($END - $START))
push
